services:
  frontend:
    image: "frontend"
    ports:
      - "3000:3000"
  backend:
    image: "backend"
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: default
    volumes:
      - ./database/example.sql:/docker-entrypoint-initdb.d/example.sql
