# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  # push: FOR NOW, JUST RUN ON REQUEST
    # branches: [ "entran/skeleton" ]
  # pull_request:
    # branches: [ "entran/skeleton" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install pip==20.2.3 
        pip install wheel
        pip install flake8 pytest numpy

        if [ -f backend/requirements.txt ]; then python -m pip install -r backend/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd backend && python -m pytest
